[2023-11-26T06:01:21.984+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T06:01:18.484235+00:00/task_id=trasform permission to 509
[2023-11-26T06:01:22.013+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T06:01:18.484235+00:00/task_id=trasform permission to 509
[2023-11-26T06:01:22.043+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.trasform manual__2023-11-26T06:01:18.484235+00:00 [queued]>
[2023-11-26T06:01:22.051+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.trasform manual__2023-11-26T06:01:18.484235+00:00 [queued]>
[2023-11-26T06:01:22.052+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T06:01:22.065+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): trasform> on 2023-11-26 06:01:18.484235+00:00
[2023-11-26T06:01:22.070+0000] {standard_task_runner.py:57} INFO - Started process 1351 to run task
[2023-11-26T06:01:22.073+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'trasform', 'manual__2023-11-26T06:01:18.484235+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpfgw7idiu']
[2023-11-26T06:01:22.076+0000] {standard_task_runner.py:85} INFO - Job 76: Subtask trasform
[2023-11-26T06:01:22.121+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T06:01:18.484235+00:00/task_id=trasform permission to 509
[2023-11-26T06:01:22.124+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.trasform manual__2023-11-26T06:01:18.484235+00:00 [running]> on host 50f4a498a395
[2023-11-26T06:01:22.373+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='trasform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T06:01:18.484235+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T06:01:18.484235+00:00'
[2023-11-26T06:01:22.394+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 22, in transform_data
    new_data = prep_data(new_data)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 60, in prep_data
    data['ts'] = pd.to_datetime(data.DateTime)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'DateTime'
[2023-11-26T06:01:22.418+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=trasform, execution_date=20231126T060118, start_date=20231126T060122, end_date=20231126T060122
[2023-11-26T06:01:22.429+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 76 for task trasform ('DataFrame' object has no attribute 'DateTime'; 1351)
[2023-11-26T06:01:22.446+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T06:01:22.463+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
